name: swipe_app
description: YouTube 영상 요약 스와이프 앱
version: 1.0.0+1
 
environment:
  sdk: '>=3.0.0 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  http: ^1.2.0
  flutter_markdown: ^0.7.1
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
 
flutter:
  uses-material-design: true
  fonts:
    - family: SCoreDream
      fonts:
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 400